### ISSUE TITLE
(suggestion) adding download button

### ISSUE THREAD

**Issue by antest1** [HitomaruKonpaku/KanColleImgBuilder#1]
I'm currently working on integrating KanColleImgBuilder with the kcanotify.

While we can download the result image by right-click on desktop, there is no way to download in the mobile.
It would be help to add such button for the mobile user.

**Comment by HitomaruKonpaku** [comment]
Hi, I added the download button.

Can you try if it is good for you?

**Comment by antest1** [comment]
It works good, thank you!
